[build]
  publish = "dist"
  command = "bash netlify-build.sh"

# Production context: all deploys from the main branch
[context.production]
  command = "bash netlify-build.sh"

# Redirects and headers are GLOBAL for all builds
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
